name: Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16.x
            - name: Install Dependencies
              run: npm install
            - name: Build
              run: npm run build
            - name: Test
              run: npm test
            - name: Prettier Check
              run: npm run prettier:check

    